// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDraftFromAsset(arg1) {
  return window['go']['main']['App']['CreateDraftFromAsset'](arg1);
}

export function CreateDraftFromPaths(arg1) {
  return window['go']['main']['App']['CreateDraftFromPaths'](arg1);
}

export function DiscardDraft(arg1) {
  return window['go']['main']['App']['DiscardDraft'](arg1);
}

export function GetAsset(arg1, arg2) {
  return window['go']['main']['App']['GetAsset'](arg1, arg2);
}

export function GetDraft(arg1) {
  return window['go']['main']['App']['GetDraft'](arg1);
}

export function GetVaultInfo() {
  return window['go']['main']['App']['GetVaultInfo']();
}

export function ListAssets() {
  return window['go']['main']['App']['ListAssets']();
}

export function ListDrafts() {
  return window['go']['main']['App']['ListDrafts']();
}

export function PublishDraft(arg1) {
  return window['go']['main']['App']['PublishDraft'](arg1);
}

export function RestoreRevision(arg1, arg2) {
  return window['go']['main']['App']['RestoreRevision'](arg1, arg2);
}

export function SetupGitVault(arg1) {
  return window['go']['main']['App']['SetupGitVault'](arg1);
}

export function SetupLocalVault() {
  return window['go']['main']['App']['SetupLocalVault']();
}

export function UpdateDraft(arg1) {
  return window['go']['main']['App']['UpdateDraft'](arg1);
}
