// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLibrary(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddLibrary'](arg1, arg2, arg3, arg4);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CompleteSleuthLogin(arg1, arg2, arg3) {
  return window['go']['main']['App']['CompleteSleuthLogin'](arg1, arg2, arg3);
}

export function CreateBlankDraft(arg1) {
  return window['go']['main']['App']['CreateBlankDraft'](arg1);
}

export function CreateCollection(arg1) {
  return window['go']['main']['App']['CreateCollection'](arg1);
}

export function CreateDraftFromAsset(arg1) {
  return window['go']['main']['App']['CreateDraftFromAsset'](arg1);
}

export function CreateDraftFromPaths(arg1) {
  return window['go']['main']['App']['CreateDraftFromPaths'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DiscardDraft(arg1) {
  return window['go']['main']['App']['DiscardDraft'](arg1);
}

export function GetAsset(arg1, arg2) {
  return window['go']['main']['App']['GetAsset'](arg1, arg2);
}

export function GetDraft(arg1) {
  return window['go']['main']['App']['GetDraft'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVaultInfo() {
  return window['go']['main']['App']['GetVaultInfo']();
}

export function HasIdentity() {
  return window['go']['main']['App']['HasIdentity']();
}

export function InstallAsset(arg1) {
  return window['go']['main']['App']['InstallAsset'](arg1);
}

export function InstallCollection(arg1) {
  return window['go']['main']['App']['InstallCollection'](arg1);
}

export function InstalledAssets() {
  return window['go']['main']['App']['InstalledAssets']();
}

export function ListAIClients() {
  return window['go']['main']['App']['ListAIClients']();
}

export function ListAssets() {
  return window['go']['main']['App']['ListAssets']();
}

export function ListCollections() {
  return window['go']['main']['App']['ListCollections']();
}

export function ListDrafts() {
  return window['go']['main']['App']['ListDrafts']();
}

export function OpenSettings() {
  return window['go']['main']['App']['OpenSettings']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function PickFilesForDraft() {
  return window['go']['main']['App']['PickFilesForDraft']();
}

export function PickFolderForDraft() {
  return window['go']['main']['App']['PickFolderForDraft']();
}

export function PublishDraft(arg1) {
  return window['go']['main']['App']['PublishDraft'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RestoreRevision(arg1, arg2) {
  return window['go']['main']['App']['RestoreRevision'](arg1, arg2);
}

export function SetCollectionMembership(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCollectionMembership'](arg1, arg2, arg3);
}

export function SetupGitVault(arg1, arg2) {
  return window['go']['main']['App']['SetupGitVault'](arg1, arg2);
}

export function SetupLocalVault(arg1) {
  return window['go']['main']['App']['SetupLocalVault'](arg1);
}

export function StartSleuthLogin(arg1) {
  return window['go']['main']['App']['StartSleuthLogin'](arg1);
}

export function SwitchProfile(arg1) {
  return window['go']['main']['App']['SwitchProfile'](arg1);
}

export function UninstallAsset(arg1) {
  return window['go']['main']['App']['UninstallAsset'](arg1);
}

export function UpdateDraft(arg1) {
  return window['go']['main']['App']['UpdateDraft'](arg1);
}
