// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAssetRepoScope(arg1, arg2) {
  return window['go']['main']['App']['AddAssetRepoScope'](arg1, arg2);
}

export function AddCollectionRepoScope(arg1, arg2) {
  return window['go']['main']['App']['AddCollectionRepoScope'](arg1, arg2);
}

export function AddLibrary(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddLibrary'](arg1, arg2, arg3, arg4);
}

export function AddTeamMember(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTeamMember'](arg1, arg2, arg3);
}

export function AvailableRepoName(arg1) {
  return window['go']['main']['App']['AvailableRepoName'](arg1);
}

export function CancelSleuthLogin() {
  return window['go']['main']['App']['CancelSleuthLogin']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CheckForUpdatesInteractively() {
  return window['go']['main']['App']['CheckForUpdatesInteractively']();
}

export function ChooseLibraryIcon(arg1) {
  return window['go']['main']['App']['ChooseLibraryIcon'](arg1);
}

export function ClearLibraryIcon(arg1) {
  return window['go']['main']['App']['ClearLibraryIcon'](arg1);
}

export function CompleteSleuthLogin(arg1, arg2, arg3) {
  return window['go']['main']['App']['CompleteSleuthLogin'](arg1, arg2, arg3);
}

export function CreateBlankDraft(arg1) {
  return window['go']['main']['App']['CreateBlankDraft'](arg1);
}

export function CreateCollection(arg1) {
  return window['go']['main']['App']['CreateCollection'](arg1);
}

export function CreateDraftFromAsset(arg1) {
  return window['go']['main']['App']['CreateDraftFromAsset'](arg1);
}

export function CreateDraftFromPaths(arg1) {
  return window['go']['main']['App']['CreateDraftFromPaths'](arg1);
}

export function CreateGitRepo(arg1) {
  return window['go']['main']['App']['CreateGitRepo'](arg1);
}

export function CreateTeam(arg1) {
  return window['go']['main']['App']['CreateTeam'](arg1);
}

export function DeleteAssets(arg1) {
  return window['go']['main']['App']['DeleteAssets'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteTeam(arg1) {
  return window['go']['main']['App']['DeleteTeam'](arg1);
}

export function DescribeLibraryRemoval(arg1) {
  return window['go']['main']['App']['DescribeLibraryRemoval'](arg1);
}

export function DiscardDraft(arg1) {
  return window['go']['main']['App']['DiscardDraft'](arg1);
}

export function GetAsset(arg1, arg2) {
  return window['go']['main']['App']['GetAsset'](arg1, arg2);
}

export function GetAssetSharing(arg1) {
  return window['go']['main']['App']['GetAssetSharing'](arg1);
}

export function GetCollectionSharing(arg1) {
  return window['go']['main']['App']['GetCollectionSharing'](arg1);
}

export function GetDraft(arg1) {
  return window['go']['main']['App']['GetDraft'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVaultInfo() {
  return window['go']['main']['App']['GetVaultInfo']();
}

export function GitHubAccount() {
  return window['go']['main']['App']['GitHubAccount']();
}

export function GitStatus() {
  return window['go']['main']['App']['GitStatus']();
}

export function HasIdentity() {
  return window['go']['main']['App']['HasIdentity']();
}

export function HideApp() {
  return window['go']['main']['App']['HideApp']();
}

export function InstalledAssets() {
  return window['go']['main']['App']['InstalledAssets']();
}

export function ListAIClients() {
  return window['go']['main']['App']['ListAIClients']();
}

export function ListAssets() {
  return window['go']['main']['App']['ListAssets']();
}

export function ListCollections() {
  return window['go']['main']['App']['ListCollections']();
}

export function ListDrafts() {
  return window['go']['main']['App']['ListDrafts']();
}

export function ListGitRepos() {
  return window['go']['main']['App']['ListGitRepos']();
}

export function ListSyncFolders() {
  return window['go']['main']['App']['ListSyncFolders']();
}

export function ListTeams() {
  return window['go']['main']['App']['ListTeams']();
}

export function OpenSettings() {
  return window['go']['main']['App']['OpenSettings']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function PickFilesForDraft() {
  return window['go']['main']['App']['PickFilesForDraft']();
}

export function PickFolderForDraft() {
  return window['go']['main']['App']['PickFolderForDraft']();
}

export function PublishDraft(arg1) {
  return window['go']['main']['App']['PublishDraft'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RemoveLibrary(arg1, arg2) {
  return window['go']['main']['App']['RemoveLibrary'](arg1, arg2);
}

export function RemoveTeamMember(arg1, arg2) {
  return window['go']['main']['App']['RemoveTeamMember'](arg1, arg2);
}

export function RenameCollection(arg1, arg2) {
  return window['go']['main']['App']['RenameCollection'](arg1, arg2);
}

export function RenameTeam(arg1, arg2) {
  return window['go']['main']['App']['RenameTeam'](arg1, arg2);
}

export function RepoAssets() {
  return window['go']['main']['App']['RepoAssets']();
}

export function RestoreRevision(arg1, arg2) {
  return window['go']['main']['App']['RestoreRevision'](arg1, arg2);
}

export function SetAssetPersonal(arg1, arg2) {
  return window['go']['main']['App']['SetAssetPersonal'](arg1, arg2);
}

export function SetAssetTeamSharing(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetAssetTeamSharing'](arg1, arg2, arg3);
}

export function SetCollectionMembership(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCollectionMembership'](arg1, arg2, arg3);
}

export function SetCollectionMembershipBulk(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCollectionMembershipBulk'](arg1, arg2, arg3);
}

export function SetCollectionTeamSharing(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCollectionTeamSharing'](arg1, arg2, arg3);
}

export function SetLibraryActive(arg1, arg2) {
  return window['go']['main']['App']['SetLibraryActive'](arg1, arg2);
}

export function SetLibraryRepoTracking(arg1, arg2) {
  return window['go']['main']['App']['SetLibraryRepoTracking'](arg1, arg2);
}

export function SetTeamAdmin(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetTeamAdmin'](arg1, arg2, arg3);
}

export function SetTeamRepository(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetTeamRepository'](arg1, arg2, arg3);
}

export function SetupGitVault(arg1, arg2) {
  return window['go']['main']['App']['SetupGitVault'](arg1, arg2);
}

export function SetupLocalVault(arg1) {
  return window['go']['main']['App']['SetupLocalVault'](arg1);
}

export function SetupSharedFolderVault(arg1, arg2) {
  return window['go']['main']['App']['SetupSharedFolderVault'](arg1, arg2);
}

export function ShareAssetWithEveryone(arg1) {
  return window['go']['main']['App']['ShareAssetWithEveryone'](arg1);
}

export function ShareCollectionWithEveryone(arg1) {
  return window['go']['main']['App']['ShareCollectionWithEveryone'](arg1);
}

export function ShowAbout() {
  return window['go']['main']['App']['ShowAbout']();
}

export function StartSleuthLogin(arg1) {
  return window['go']['main']['App']['StartSleuthLogin'](arg1);
}

export function SwitchProfile(arg1) {
  return window['go']['main']['App']['SwitchProfile'](arg1);
}

export function SyncAITools() {
  return window['go']['main']['App']['SyncAITools']();
}

export function TeamAssets() {
  return window['go']['main']['App']['TeamAssets']();
}

export function UpdateDraft(arg1) {
  return window['go']['main']['App']['UpdateDraft'](arg1);
}
