// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddLibrary(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.VaultInfo>;

export function AddTeamMember(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function CancelSleuthLogin():Promise<void>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function CompleteSleuthLogin(arg1:string,arg2:string,arg3:string):Promise<main.VaultInfo>;

export function CreateBlankDraft(arg1:string):Promise<main.Draft>;

export function CreateCollection(arg1:string):Promise<main.Collection>;

export function CreateDraftFromAsset(arg1:string):Promise<main.Draft>;

export function CreateDraftFromPaths(arg1:Array<string>):Promise<main.Draft>;

export function CreateTeam(arg1:string):Promise<main.TeamInfo>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DiscardDraft(arg1:string):Promise<void>;

export function GetAsset(arg1:string,arg2:string):Promise<main.AssetDetail>;

export function GetAssetSharing(arg1:string):Promise<main.AssetSharing>;

export function GetCollectionSharing(arg1:string):Promise<main.AssetSharing>;

export function GetDraft(arg1:string):Promise<main.Draft>;

export function GetSettings():Promise<main.Settings>;

export function GetVaultInfo():Promise<main.VaultInfo>;

export function GitStatus():Promise<main.GitStatusInfo>;

export function HasIdentity():Promise<boolean>;

export function InstallAsset(arg1:string):Promise<main.InstallResult>;

export function InstallCollection(arg1:string):Promise<main.InstallResult>;

export function InstalledAssets():Promise<Array<main.InstalledAssetInfo>>;

export function ListAIClients():Promise<Array<main.AIClient>>;

export function ListAssets():Promise<Array<main.AssetCard>>;

export function ListCollections():Promise<Array<main.Collection>>;

export function ListDrafts():Promise<Array<main.Draft>>;

export function ListSyncFolders():Promise<Array<main.SyncFolderOption>>;

export function ListTeams():Promise<Array<main.TeamInfo>>;

export function OpenSettings():Promise<void>;

export function PickDirectory():Promise<string>;

export function PickFilesForDraft():Promise<main.Draft>;

export function PickFolderForDraft():Promise<main.Draft>;

export function PublishDraft(arg1:string):Promise<main.AssetCard>;

export function Quit():Promise<void>;

export function RemoveTeamMember(arg1:string,arg2:string):Promise<void>;

export function RestoreRevision(arg1:string,arg2:string):Promise<void>;

export function SetAssetTeamSharing(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetCollectionMembership(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetCollectionTeamSharing(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetTeamAdmin(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetupGitVault(arg1:string,arg2:string):Promise<main.VaultInfo>;

export function SetupLocalVault(arg1:string):Promise<main.VaultInfo>;

export function SetupSharedFolderVault(arg1:string,arg2:string):Promise<main.VaultInfo>;

export function ShareAssetWithEveryone(arg1:string):Promise<void>;

export function ShareCollectionWithEveryone(arg1:string):Promise<void>;

export function StartSleuthLogin(arg1:string):Promise<main.SleuthLoginStart>;

export function SwitchProfile(arg1:string):Promise<main.VaultInfo>;

export function TeamAssets():Promise<Record<string, Array<string>>>;

export function UninstallAsset(arg1:string):Promise<void>;

export function UpdateDraft(arg1:main.Draft):Promise<main.Draft>;
