// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function CreateBlankDraft(arg1:string):Promise<main.Draft>;

export function CreateCollection(arg1:string):Promise<main.Collection>;

export function CreateDraftFromAsset(arg1:string):Promise<main.Draft>;

export function CreateDraftFromPaths(arg1:Array<string>):Promise<main.Draft>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DiscardDraft(arg1:string):Promise<void>;

export function GetAsset(arg1:string,arg2:string):Promise<main.AssetDetail>;

export function GetDraft(arg1:string):Promise<main.Draft>;

export function GetSettings():Promise<main.Settings>;

export function GetVaultInfo():Promise<main.VaultInfo>;

export function HasIdentity():Promise<boolean>;

export function InstallAsset(arg1:string):Promise<main.InstallResult>;

export function InstallCollection(arg1:string):Promise<main.InstallResult>;

export function InstalledAssets():Promise<Array<main.InstalledAssetInfo>>;

export function ListAIClients():Promise<Array<main.AIClient>>;

export function ListAssets():Promise<Array<main.AssetCard>>;

export function ListCollections():Promise<Array<main.Collection>>;

export function ListDrafts():Promise<Array<main.Draft>>;

export function OpenSettings():Promise<void>;

export function PickFilesForDraft():Promise<main.Draft>;

export function PickFolderForDraft():Promise<main.Draft>;

export function PublishDraft(arg1:string):Promise<main.AssetCard>;

export function Quit():Promise<void>;

export function RestoreRevision(arg1:string,arg2:string):Promise<void>;

export function SetCollectionMembership(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetupGitVault(arg1:string,arg2:string):Promise<main.VaultInfo>;

export function SetupLocalVault(arg1:string):Promise<main.VaultInfo>;

export function SwitchProfile(arg1:string):Promise<main.VaultInfo>;

export function UninstallAsset(arg1:string):Promise<void>;

export function UpdateDraft(arg1:main.Draft):Promise<main.Draft>;
