// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAsset(arg1:string,arg2:string):Promise<main.AssetDetail>;

export function GetVaultInfo():Promise<main.VaultInfo>;

export function ListAssets():Promise<Array<main.AssetCard>>;

export function SetupGitVault(arg1:string):Promise<main.VaultInfo>;

export function SetupLocalVault():Promise<main.VaultInfo>;
